import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Preview, ResponseData } from '../types';
import { demoWorkspace } from '../lib/workspace';
import { useWorkbench } from './useWorkbench';
import { api } from '../lib/ipc';

vi.mock('../lib/ipc', () => ({ desktop: true, api: { load: vi.fn(), save: vi.fn(), preview: vi.fn(), send: vi.fn(), cancel: vi.fn(), exportCurl: vi.fn(), pickFile: vi.fn(), readProjectFile: vi.fn(), writeProjectFile: vi.fn(), backup: vi.fn() } }));
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((a, b) => { resolve = a; reject = b; }); return { promise, resolve, reject }; }
const preview: Preview = { url: 'https://api.example.com/users', environmentName: '开发环境', serviceName: '用户服务', isProduction: false, resolvedVariables: [] };
const response = (executionId: string): ResponseData => ({ executionId, status: 200, statusText: 'OK', body: '{}', headers: [], sizeBytes: 2, durationMs: 10, truncated: false, environmentName: '开发环境', url: preview.url });
beforeEach(() => {
  vi.resetAllMocks();
  vi.mocked(api.load).mockResolvedValue(demoWorkspace());
  vi.mocked(api.preview).mockResolvedValue(preview);
  vi.mocked(api.cancel).mockResolvedValue(undefined);
  vi.mocked(api.save).mockImplementation(async workspace => ({ ...workspace, revision: workspace.revision + 1 }));
});
afterEach(cleanup);
describe('IPC、快照与并发', () => {
  it('关闭运行中的标签不取消请求，响应仍归属原接口并可重新打开', async () => {
    const pending = deferred<ResponseData>();
    vi.mocked(api.send).mockReturnValue(pending.promise);
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let sending!: Promise<void>;
    act(() => { sending = result.current.execute(); });
    await waitFor(() => expect(api.send).toHaveBeenCalledTimes(1));
    const executionId = vi.mocked(api.send).mock.calls[0][0].executionId;
    act(() => result.current.closeTab('demo-list'));
    expect(result.current.hasRunning).toBe(true);
    expect(result.current.request).toBeUndefined();
    expect(api.cancel).not.toHaveBeenCalled();
    await act(async () => { pending.resolve(response(executionId)); await sending; });
    act(() => result.current.selectRequest('demo-list'));
    expect(result.current.execution?.response?.executionId).toBe(executionId);
  });
  it('删除接口后清理失效标签，不保留另一接口的执行面板', async () => {
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    act(() => result.current.mutate(w => ({ ...w, requests: w.requests.filter(r => r.id !== 'demo-list') })));
    expect(result.current.openTabs).not.toContain('demo-list');
    expect(result.current.request).toBeUndefined();
    expect(result.current.selectedId).toBeNull();
  });
  it.each(['取消', '保存失败'])('cURL 导出%s时不触发导出或复制', async outcome => {
    vi.mocked(api.save).mockRejectedValueOnce(new Error('save failed'));
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    act(() => result.current.mutate(w => ({ ...w })));
    let copying!: Promise<void>;
    act(() => { copying = result.current.copyCurl(); });
    await act(async () => { result.current.confirmation!.resolve(outcome !== '取消'); result.current.setConfirmation(null); await copying; });
    expect(api.exportCurl).not.toHaveBeenCalled();
    expect(result.current.dirty).toBe(true);
    expect(result.current.busy).toBe(false);
  });
  it('文件对话框期间不允许修改临时变量，取消选择不产生草稿', async () => {
    const pending = deferred<string | null>();
    vi.mocked(api.pickFile).mockReturnValue(pending.promise);
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let picking!: Promise<string | null>;
    act(() => { picking = result.current.pickFile(); });
    expect(result.current.busy).toBe(true);
    act(() => result.current.setTemporary([{ id: 't', key: 'token', value: 'bad', enabled: true }]));
    expect(result.current.temporary).toHaveLength(0);
    await act(async () => { pending.resolve(null); expect(await picking).toBeNull(); });
    expect(result.current.dirty).toBe(false);
    expect(result.current.busy).toBe(false);
  });
  it('关闭标签不删除草稿、临时变量或运行结果，重新打开可恢复', async () => {
    vi.mocked(api.send).mockImplementation(async input => response(input.executionId));
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    await act(() => result.current.execute());
    act(() => result.current.setTemporary([{ id: 't', key: 'page', value: '2', enabled: true }]));
    act(() => result.current.mutate(w => ({ ...w, requests: w.requests.map(r => r.id === 'demo-list' ? { ...r, path: '/draft' } : r) })));
    act(() => result.current.closeTab('demo-list'));
    expect(result.current.selectedId).toBeNull();
    expect(result.current.workspace.requests.find(r => r.id === 'demo-list')?.path).toBe('/draft');
    act(() => result.current.selectRequest('demo-list'));
    await act(async () => { result.current.confirmation?.resolve(true); result.current.setConfirmation(null); });
    expect(result.current.openTabs).toEqual(['demo-list']);
    expect(result.current.request?.path).toBe('/draft');
    expect(result.current.execution?.response?.status).toBe(200);
    expect(result.current.temporary[0].value).toBe('2');
  });
  it('复制 cURL 保存确认前不导出，确认后仅复制原生脱敏结果且不发送', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } });
    vi.mocked(api.exportCurl).mockResolvedValue("curl 'https://example.com' -H 'Authorization: [REDACTED]'");
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    act(() => result.current.mutate(w => ({ ...w, requests: w.requests.map(r => ({ ...r, path: '/draft' })) })));
    let copying!: Promise<void>;
    act(() => { copying = result.current.copyCurl(); });
    expect(result.current.busy).toBe(true);
    expect(api.exportCurl).not.toHaveBeenCalled();
    await act(async () => { result.current.confirmation!.resolve(true); result.current.setConfirmation(null); await copying; });
    expect(api.save).toHaveBeenCalledTimes(1);
    expect(api.exportCurl).toHaveBeenCalledWith(expect.objectContaining({ request: expect.objectContaining({ path: '/draft' }), productionConfirmed: false }));
    expect(writeText).toHaveBeenCalledWith("curl 'https://example.com' -H 'Authorization: [REDACTED]'");
    expect(api.send).not.toHaveBeenCalled();
  });
  it('保存传完整快照，连续保存使用服务器返回的新 revision', async () => {
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request?.id).toBe('demo-list'));
    act(() => result.current.mutate(w => ({ ...w, requests: w.requests.map(r => ({ ...r, name: `${r.name}已编辑` })) })));
    await act(() => result.current.save());
    expect(api.save).toHaveBeenCalledWith(expect.objectContaining({ revision: 0, bindings: expect.any(Array), requests: expect.any(Array), variables: expect.any(Array) }));
    expect(result.current.workspace.revision).toBe(1);
    await act(() => result.current.save());
    expect(vi.mocked(api.save).mock.calls[1][0].revision).toBe(1);
    expect(result.current.workspace.revision).toBe(2);
  });
  it('响应和取消绑定原始执行 ID，切换接口不串响应', async () => {
    const pending = deferred<ResponseData>();
    vi.mocked(api.send).mockReturnValue(pending.promise);
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let sending!: Promise<void>;
    act(() => { sending = result.current.execute(); });
    await waitFor(() => expect(api.send).toHaveBeenCalledTimes(1));
    const id = vi.mocked(api.send).mock.calls[0][0].executionId;
    await act(() => result.current.cancel());
    expect(api.cancel).toHaveBeenCalledWith(id);
    act(() => result.current.selectRequest('demo-create'));
    expect(result.current.execution).toBeUndefined();
    await act(async () => { pending.resolve(response(id)); await sending; });
    expect(result.current.execution).toBeUndefined();
    act(() => result.current.selectRequest('demo-list'));
    expect(result.current.execution?.response?.executionId).toBe(id);
  });
  it('同一接口准备中及发送中不能重复发送', async () => {
    const pending = deferred<ResponseData>();
    vi.mocked(api.send).mockReturnValue(pending.promise);
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let sending!: Promise<void>;
    act(() => { sending = result.current.execute(); void result.current.execute(); });
    await waitFor(() => expect(api.send).toHaveBeenCalledTimes(1));
    await act(() => result.current.execute());
    expect(api.send).toHaveBeenCalledTimes(1);
    await act(async () => { pending.resolve(response(vi.mocked(api.send).mock.calls[0][0].executionId)); await sending; });
  });
  it('生产环境确认前不发送，确认后带 productionConfirmed', async () => {
    vi.mocked(api.preview).mockResolvedValue({ ...preview, isProduction: true, environmentName: '生产环境' });
    vi.mocked(api.send).mockImplementation(async input => response(input.executionId));
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let sending!: Promise<void>;
    act(() => { sending = result.current.execute(); });
    await waitFor(() => expect(result.current.confirmation?.title).toBe('确认发送到生产环境'));
    expect(api.send).not.toHaveBeenCalled();
    await act(async () => { result.current.confirmation!.resolve(true); result.current.setConfirmation(null); await sending; });
    expect(api.send).toHaveBeenCalledWith(expect.objectContaining({ productionConfirmed: true }));
  });
  it('旧请求完成不能解锁另一请求仍在进行的预览', async () => {
    const first = deferred<ResponseData>();
    const secondPreview = deferred<Preview>();
    vi.mocked(api.send).mockReturnValue(first.promise);
    const { result } = renderHook(useWorkbench);
    await waitFor(() => expect(result.current.request).toBeTruthy());
    let sending!: Promise<void>;
    act(() => { sending = result.current.execute(); });
    await waitFor(() => expect(api.send).toHaveBeenCalledTimes(1));
    act(() => result.current.selectRequest('demo-create'));
    vi.mocked(api.preview).mockReturnValueOnce(secondPreview.promise);
    let preparing!: Promise<void>;
    act(() => { preparing = result.current.execute(true); });
    expect(result.current.busy).toBe(true);
    await act(async () => { first.resolve(response(vi.mocked(api.send).mock.calls[0][0].executionId)); await sending; });
    expect(result.current.busy).toBe(true);
    await act(async () => { secondPreview.resolve(preview); await preparing; });
    expect(result.current.busy).toBe(false);
  });
});
